name: Master Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: master

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5
      with:
        ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh ${{ vars.SERVER_USER }}@${{ vars.SERVER_ADDRESS }} "cd learn-gh-actions && git pull origin main"
